org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
# AGP 8.5.2 belum resmi menguji compileSdk 35 — flag ini menekan warning-nya.
# Saat upgrade AGP ke 8.6+ nanti, baris ini boleh dihapus.
android.suppressUnsupportedCompileSdk=35
